local timervalue = 10 --timer value in minutes for the temporary traits
local TWE_Events = {}
local TraitEndTime = 0
local ViewerName = ""
----positive items table
local HelpTheStreamer ={ "Base.BaseballBat", "Base.HuntingKnife", "Base.Axe", "Base.WristWatch_Right_DigitalRed", "Base.Crowbar", "Base.HandAxe", "Base.Burger", "Base.Crisps", "Base.Sandwich", "Base.BeerBottle", "Base.Pop","Base.Belt2","Base.TinnedBeans" }
----negative items table
local TrollTheStreamer = { "Base.Generator", "Base.LogStacks4", "Base.Dirtbag", "Base.Sandbag" }
-----Air Events Presets
local TWE_Airevents = {"military","police","news_chopper","raiders","FEMA_drop","jet","survivor_heli"}
-----Temporary traits table
local TWETraitsTable = {[1]="Deaf",[2]="Thinskinned",[3]="AllThumbs",[4]="Cowardly",[5]="Hemophobic",[6]="SundayDriver",[7]="Graceful",[8]="KeenHearing",[9]="ThickSkinned",[10]="SpeedDemon",[11]="Jogger",[12]="Inconspicuous"}
local TWETempTraitsTable = {}



--processes the EventsTable generated by getreward
function processEvent(EventsTable)
    local playerChar = getPlayer()
	if EventsTable then    
		ViewerName = EventsTable["viewer"]
		if EventsTable["zombies"] and EventsTable["zombies"] == "true" then
			print("------------=Twitch Events: zombies=------------")
			playerChar:Say(EventsTable["viewer"] .. " sent " ..EventsTable["zedquant"] .. " 좀비ㅎzombies")
			--local Zedx, Zedy, wz = LSpawnLoc();
			local zedquant = tonumber(EventsTable["zedquant"])	
				if isClient() then
				local Zedx, Zedy, Zedz = SpawnLoc(50)
				ServerEvent = {["Etype"] = "Zedspawn", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["PlayerChar"] = playerchar }
				--playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
				sendClientCommand("TWEEvents", "Zedspawn", ServerEvent); -- Trigger Event from Client to Server
				else
				local Zedx, Zedy, Zedz = SpawnLoc(85)
				createHordeFromTo(Zedx, Zedy, playerChar:getX(), playerChar:getY(), zedquant)					
				end
		end


	
        if EventsTable["gifts"] and tonumber(EventsTable["gifts"]) > 0 then
           print("------------=Twitch Events: gift =------------")
		   TWE_Events.GiftItems(tonumber(EventsTable["gifts"]))
        end
        if EventsTable["helicopter"] and tonumber(EventsTable["helicopter"]) > 0 then
            if tonumber(EventsTable["helicopter"]) == 1 then 
			print("------------=Twitch Events: Air Event=------------")
			getPlayer():Say(EventsTable["viewer"] .. " called a Military Heli")
			local heli = getFreeHelicopter("military")
			local playerChar = getPlayer()
			heli:launch(playerChar, false)
			end
			if tonumber(EventsTable["helicopter"]) == 2 then 
			print("------------=Twitch Events: Air Event=------------")
			getPlayer():Say(EventsTable["viewer"] .. " called a News Heli")
			local heli = getFreeHelicopter("police")
			local playerChar = getPlayer()
			heli:launch(playerChar, false)
			end
			if tonumber(EventsTable["helicopter"]) == 3 then 
			print("------------=Twitch Events: Air Event=------------")
			getPlayer():Say(EventsTable["viewer"] .. " called a News Heli")
			local heli = getFreeHelicopter("news_chopper")
			local playerChar = getPlayer()
			heli:launch(playerChar, false)
			end
			if tonumber(EventsTable["helicopter"]) == 4 then 
			print("------------=Twitch Events: Air Event=------------")
			getPlayer():Say(EventsTable["viewer"] .. " called a Raiders Heli")
			local heli = getFreeHelicopter("raiders")
			local playerChar = getPlayer()
			heli:launch(playerChar, false)
			end		
			if tonumber(EventsTable["helicopter"]) == 5 then 
			print("------------=Twitch Events: Air Event=------------")
			getPlayer():Say(EventsTable["viewer"] .. " called a Air Drop")
			local heli = getFreeHelicopter("FEMA_drop")
			local playerChar = getPlayer()
			heli:launch(playerChar, false)
			end
			if tonumber(EventsTable["helicopter"]) == 6 then 
			print("------------=Twitch Events: Air Event=------------")
			getPlayer():Say(EventsTable["viewer"] .. " called a jet")
			local heli = getFreeHelicopter("jet")
			local playerChar = getPlayer()
			heli:launch(playerChar, false)
			end
			if tonumber(EventsTable["helicopter"]) == 7 then 
			print("------------=Twitch Events: Air Event=------------")
			local randomAir = TWE_Airevents[ZombRand(1,7)]
			local heli = getFreeHelicopter(randomAir)
			local playerChar = getPlayer()
			--getPlayer():Say("randomAir: " ..randomAir )
			getPlayer():Say(EventsTable["viewer"] .. " bought a random Air Event")
			heli:launch(playerChar, false)
			end
        end
		if EventsTable["gas"] == "true" then --car events begin
		TWE_Events.TWECars("GasTank")
		end
		if EventsTable["tire"] == "true" then
		TWE_Events.TWECars("FlatTire")
		end
		if EventsTable["muffler"] == "true" then
		TWE_Events.TWECars("Muffler")
		end
		if EventsTable["battery"] == "true" then
		TWE_Events.TWECars("Battery")
		end
		if EventsTable["engine"] == "true" then -- car events end
		TWE_Events.TWECars("Engine")
		end	
		if EventsTable["trait"] and tonumber(EventsTable["trait"]) > 0 then -- traits begin
		 TWETableTraitsTrigger(tonumber(EventsTable["trait"]))
	end
	end
end
--temporary traits trigger---
function TWETableTraitsTrigger(MyTrait)
		local playerChar = getPlayer()
		local calendar = PZCalendar.getInstance()
		local hour = calendar:get(Calendar.HOUR_OF_DAY)
		local minute = calendar:get(Calendar.MINUTE)
		local second = calendar:get(Calendar.SECOND)
		if hour == 0 then --check if its 0, if true replaces 0 with 24
		TraitEndTime = (24 * 60 + minute + timervalue ) * 60 + second
		else TraitEndTime = (hour * 60 + minute + timervalue) * 60 + second
		end	
		if not playerChar:HasTrait(TWETraitsTable[MyTrait]) then
        playerChar:getTraits():add(TWETraitsTable[MyTrait]);
		table.insert(TWETempTraitsTable, {trait = TWETraitsTable[MyTrait], endtime = TraitEndTime})
		HaloTextHelper.addTextWithArrow(playerChar, getText("UI_trait_"..TWETraitsTable[MyTrait]), true, HaloTextHelper.getColorGreen())
        Events.EveryOneMinute.Remove(TWE_TraitCheck);
        Events.EveryOneMinute.Add(TWE_TraitCheck);
    end
end
--temporary traits timer check---
function TWE_TraitCheck()
		local playerChar = getPlayer()
		local calendar = PZCalendar.getInstance()
		local hour = calendar:get(Calendar.HOUR_OF_DAY)
		local minute = calendar:get(Calendar.MINUTE)
		local second = calendar:get(Calendar.SECOND)
		if hour == 0 then --check if its 0, if true replaces 0 with 24
		currentTime = (24 * 60 + minute) * 60 + second
		else currentTime = (hour * 60 + minute) * 60 + second
		end	
        for i, v in ipairs(TWETempTraitsTable) do
        local trait = v.trait
        local endtime = v.endtime
        if endtime <= currentTime then
			print("Removing trait: " .. trait)
			print("Endtime: " .. endtime)
			playerChar:getTraits():remove(trait);
            HaloTextHelper.addTextWithArrow(playerChar, getText("UI_trait_"..trait), false, HaloTextHelper.getColorRed())     
            table.remove(TWETempTraitsTable, i)
            if #TWETempTraitsTable == 0 then
                Events.EveryOneMinute.Remove(TWE_TraitCheck)
                break
            end
        end
		end

end
--car event actions
function TWE_Events.TWECars(Mypart)
    local playerChar = getPlayer()
	local mycar = playerChar:getVehicle()
    local TireSet = { "TireRearRight", "TireRearLeft"," TireFrontRight", "TireFrontLeft"}
    local WhichTire = ZombRand(1,5)
    if mycar ~= nil then
        for i = mycar:getPartCount()-1,0,-1 do
            local part = mycar:getPartByIndex(i)
            local cat = part:getCategory()
            local item = part:getId()
            if item ~=  nil then
                if Mypart == "Engine" and item == Mypart then
                    playerChar:Say("No no no... don't die on me now!!")
					part:setCondition(0)
                end
                if Mypart == "FlatTire" then
                    if TireSet[WhichTire] == item then
                        VehicleUtils.RemoveTire(part, true)
                    end
                    end
                end
                if Mypart == "GasTank" and item == Mypart then
                part:setContainerContentAmount(0)
                end
                if Mypart == "Muffler" and item == Mypart then
                part:setCondition(0)
                end
                if Mypart == "Battery" and item == Mypart then
                part:setCondition(0)
                end
            end
        end
end
--gifts event actions
function TWE_Events.GiftItems(whatkind)
local player = getSpecificPlayer(0)
local inv = player:getInventory()
local Helpmeitem = 0
local Trollmeitem = 0
	if whatkind == 1 then
		Helpmeitem = ZombRand(1,14)
		inv:AddItem(HelpTheStreamer[Helpmeitem])
		player:Say("Thank you for the " .. getItemNameFromFullType(HelpTheStreamer[Helpmeitem]) .. " " .. ViewerName)
	elseif whatkind == 2 then
		Trollmeitem = ZombRand(1,5)
		inv:AddItem(TrollTheStreamer[Trollmeitem])
		player:Say("Uau... a " .. getItemNameFromFullType(TrollTheStreamer[Trollmeitem]).. " " .. ViewerName .. " really?!")
	elseif whatkind == 3 then
		Trollmeitem = ZombRand(1,5)
		inv:AddItem(TrollTheStreamer[Trollmeitem])
		Helpmeitem = ZombRand(1,14)
		inv:AddItem(HelpTheStreamer[Helpmeitem])
		Ggift = HelpTheStreamer[Helpmeitem]
		Bgift = TrollTheStreamer[Trollmeitem]
		player:Say("So a " .. getItemNameFromFullType(HelpTheStreamer[Helpmeitem]) .. " with a " .. getItemNameFromFullType(TrollTheStreamer[Trollmeitem]) .. "! You have strange tastes " .. ViewerName .."!")
		end
end

--spawn x,y,z randomizer needs improvement
function SpawnLoc(maxValue)
    local mx = getPlayer():getX();
    local my = getPlayer():getY();
    local mz = getPlayer():getZ();
    --local DistOffset = ZombRand(40,85);
    local DistOffset = ZombRand(25,maxValue);
	local Operation = ZombRand(1,5);
    local logic ={
        function() mx = mx + DistOffset end,
        function() mx = mx - DistOffset end,
        function() my = my + DistOffset end,
        function() my = my - DistOffset end
    }
    logic[Operation]()
    return mx,my,mz
end

return TWE_Events



